/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/tasks/{id}/trigger': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Dispatch a task's outbound trigger immediately.
     * @description Resolves the task by id, dispatches it through the integration module registry, and returns the outcome. Does not write back to the vault — no @last_triggered stamp. The surgical patcher and writeback orchestration are M2/M3 work; this endpoint exists to prove the dispatch path in M1.
     */
    post: operations['triggerTask']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/subscriptions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Enrol a push subscription.
     * @description Stores a Web Push subscription object as returned by `PushSubscription.toJSON()` in the browser. Persisted to the /config volume, never to the vault (SDD.md §2.3).
     */
    post: operations['createSubscription']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/subscriptions/unsubscribe': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Remove a push subscription.
     * @description Identified by endpoint URL rather than a synthetic id — a push subscription's endpoint is already its unique key (SDD.md G14: the same pruning a 404/410 from the push service triggers).
     */
    post: operations['deleteSubscription']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/vapid-public-key': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Fetch the VAPID public key for push enrolment.
     * @description Base64url-encoded, suitable as `applicationServerKey` in `PushManager.subscribe()`. The keypair lives on the /config volume and survives restarts (SDD.md §2.3).
     */
    get: operations['getVapidPublicKey']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** @description Unique across the whole vault (SDD.md G1, G3). */
    TaskId: string
    /** @description What the integration module reported back, not a delivery receipt. "accepted" means the push service accepted the message for delivery — Web Push returns no delivery confirmation (SDD.md §3, state reference). */
    TriggerOutcome: {
      task_id: components['schemas']['TaskId']
      /** @description The integration module that handled dispatch, e.g. ios_notifications. */
      target: string
      /** Format: date-time */
      dispatched_at: string
      accepted: boolean
      /** @description Human-readable outcome detail, e.g. a delivery error. */
      detail?: string | null
    }
    /** @description The shape a browser's PushSubscription.toJSON() produces. */
    PushSubscription: {
      /** Format: uri */
      endpoint: string
      /** Format: date-time */
      expirationTime?: string | null
      keys: {
        p256dh: string
        auth: string
      }
    }
    Error: {
      error: {
        code: string
        message: string
        details?: {
          [key: string]: unknown
        } | null
      }
    }
  }
  responses: {
    /** @description An unexpected error occurred. */
    UnexpectedError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['Error']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  triggerTask: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['schemas']['TaskId']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The task was resolved and dispatch was attempted. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TriggerOutcome']
        }
      }
      /** @description No task with this id is known to the index. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      default: components['responses']['UnexpectedError']
    }
  }
  createSubscription: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PushSubscription']
      }
    }
    responses: {
      /** @description The subscription was stored. */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PushSubscription']
        }
      }
      /** @description The subscription object is malformed. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      default: components['responses']['UnexpectedError']
    }
  }
  deleteSubscription: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** Format: uri */
          endpoint: string
        }
      }
    }
    responses: {
      /** @description The subscription was removed, or was already absent. */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description The request body is missing or malformed. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      default: components['responses']['UnexpectedError']
    }
  }
  getVapidPublicKey: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The current VAPID public key. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            public_key: string
          }
        }
      }
      /** @description No VAPID keypair has been provisioned on /config yet. */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Error']
        }
      }
      default: components['responses']['UnexpectedError']
    }
  }
}
