package api

import (
	"net/http"

	"github.com/cosmin2dor/vakt/internal/model"
)

// ListDirectivesHandler serves the directive registry (model.Directives),
// converted to the OpenAPI DTO, so the Smart Editor's autocomplete never
// drifts ahead of what the daemon actually parses (SDD.md §2.5).
func ListDirectivesHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		out := make([]model.Directive, 0, len(model.Directives))
		for _, d := range model.Directives {
			out = append(out, directiveDTO(d))
		}
		writeJSON(w, http.StatusOK, out)
	}
}

// directiveDTO converts a registry entry (internal/model, generated by
// cmd/gen-directives) to the OpenAPI-generated response type.
func directiveDTO(d model.DirectiveDescriptor) model.Directive {
	var values *[]string
	if d.Values != nil {
		values = &d.Values
	}
	return model.Directive{
		Name:          d.Name,
		ValueType:     d.ValueType,
		Values:        values,
		Pattern:       d.Pattern,
		Arity:         d.Arity,
		Required:      d.Required,
		SystemWritten: d.SystemWritten,
		UiHelper:      d.UIHelper,
	}
}
