// Package model provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package model

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	Error struct {
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// PushSubscription The shape a browser's PushSubscription.toJSON() produces.
type PushSubscription struct {
	Endpoint       string     `json:"endpoint"`
	ExpirationTime *time.Time `json:"expirationTime,omitempty"`
	Keys           struct {
		Auth   string `json:"auth"`
		P256dh string `json:"p256dh"`
	} `json:"keys"`
}

// TaskId Unique across the whole vault (SDD.md G1, G3).
type TaskId = string

// TriggerOutcome What the integration module reported back, not a delivery receipt. "accepted" means the push service accepted the message for delivery — Web Push returns no delivery confirmation (SDD.md §3, state reference).
type TriggerOutcome struct {
	Accepted bool `json:"accepted"`

	// Detail Human-readable outcome detail, e.g. a delivery error.
	Detail       *string   `json:"detail,omitempty"`
	DispatchedAt time.Time `json:"dispatched_at"`

	// Target The integration module that handled dispatch, e.g. ios_notifications.
	Target string `json:"target"`

	// TaskId Unique across the whole vault (SDD.md G1, G3).
	TaskId TaskId `json:"task_id"`
}

// UnexpectedError defines model for UnexpectedError.
type UnexpectedError = Error

// DeleteSubscriptionJSONBody defines parameters for DeleteSubscription.
type DeleteSubscriptionJSONBody struct {
	Endpoint string `json:"endpoint"`
}

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = PushSubscription

// DeleteSubscriptionJSONRequestBody defines body for DeleteSubscription for application/json ContentType.
type DeleteSubscriptionJSONRequestBody DeleteSubscriptionJSONBody
